name: elektronn2-env
channels:
  - conda-forge

dependencies:
  - python =2.7
  - numpy =1.12
  - scipy =0.19
  - matplotlib =1.5
  - scikit-learn =0.18
  - scikit-image =0.13
  - h5py =2.7
  - theano =0.9
  - pygpu =0.6
  - future =0.16
  - tqdm =4.11
  - numba =0.32
  - colorlog =2.10
  - pydotplus =2.0
  - seaborn =0.7
  - prompt_toolkit =1.0
  - jedi =0.10
  - psutil =5.2
  - ipython >=5.3  # 6 doesn't work with py2
  - sphinx =1.6
  - sphinx_rtd_theme =0.2.4
  - pip:
    - git+https://github.com/mdraw/knossos_utils
